import { Region } from '../common/enums/region.enum';
import { RegionConfig } from './region-config.interface';

export const REGION_CONFIGS: Record<Region, RegionConfig> = {
  [Region.UAE]: {
    defaultCurrency: 'AED',
    baseCurrency: 'AED',
    taxAuthority: 'Federal Tax Authority',
    defaultTaxRate: 5.0,
    vatNumberLabel: 'VAT Number',
    trnLabel: 'TRN',
    supportedCurrencies: ['AED', 'USD', 'EUR', 'GBP', 'SAR'],
    invoiceTitle: 'TAX INVOICE',
    appBrandName: 'SelfAccounting.AI',
    complianceBody: 'FTA',
    emailBrandName: 'SelfAccounting.AI',
  },
  [Region.SAUDI]: {
    defaultCurrency: 'SAR',
    baseCurrency: 'SAR',
    taxAuthority: 'Zakat, Tax and Customs Authority',
    defaultTaxRate: 15.0,
    vatNumberLabel: 'VAT Number',
    trnLabel: 'VAT Registration Number',
    supportedCurrencies: ['SAR', 'USD', 'EUR', 'GBP', 'AED'],
    invoiceTitle: 'TAX INVOICE',
    appBrandName: 'SelfAccounting.AI',
    complianceBody: 'ZATCA',
    emailBrandName: 'SelfAccounting.AI',
  },
  [Region.OMAN]: {
    defaultCurrency: 'OMR',
    baseCurrency: 'OMR',
    taxAuthority: 'Tax Authority',
    defaultTaxRate: 5.0,
    vatNumberLabel: 'VAT Number',
    trnLabel: 'Tax Registration Number',
    supportedCurrencies: ['OMR', 'USD', 'EUR', 'GBP', 'AED'],
    invoiceTitle: 'TAX INVOICE',
    appBrandName: 'SelfAccounting.AI',
    complianceBody: 'Tax Authority',
    emailBrandName: 'SelfAccounting.AI',
  },
  [Region.KUWAIT]: {
    defaultCurrency: 'KWD',
    baseCurrency: 'KWD',
    taxAuthority: 'Kuwait Tax Authority',
    defaultTaxRate: 5.0,
    vatNumberLabel: 'VAT Number',
    trnLabel: 'Tax Registration Number',
    supportedCurrencies: ['KWD', 'USD', 'EUR', 'GBP', 'AED'],
    invoiceTitle: 'TAX INVOICE',
    appBrandName: 'SelfAccounting.AI',
    complianceBody: 'Kuwait Tax Authority',
    emailBrandName: 'SelfAccounting.AI',
  },
  [Region.BAHRAIN]: {
    defaultCurrency: 'BHD',
    baseCurrency: 'BHD',
    taxAuthority: 'National Bureau for Revenue',
    defaultTaxRate: 10.0,
    vatNumberLabel: 'VAT Number',
    trnLabel: 'VAT Registration Number',
    supportedCurrencies: ['BHD', 'USD', 'EUR', 'GBP', 'AED'],
    invoiceTitle: 'TAX INVOICE',
    appBrandName: 'SelfAccounting.AI',
    complianceBody: 'NBR',
    emailBrandName: 'SelfAccounting.AI',
  },
  [Region.QATAR]: {
    defaultCurrency: 'QAR',
    baseCurrency: 'QAR',
    taxAuthority: 'General Tax Authority',
    defaultTaxRate: 5.0,
    vatNumberLabel: 'VAT Number',
    trnLabel: 'Tax Registration Number',
    supportedCurrencies: ['QAR', 'USD', 'EUR', 'GBP', 'AED'],
    invoiceTitle: 'TAX INVOICE',
    appBrandName: 'SelfAccounting.AI',
    complianceBody: 'GTA',
    emailBrandName: 'SelfAccounting.AI',
  },
  [Region.INDIA]: {
    defaultCurrency: 'INR',
    baseCurrency: 'INR',
    taxAuthority: 'Goods and Services Tax Authority',
    defaultTaxRate: 18.0,
    vatNumberLabel: 'GST Number',
    trnLabel: 'GSTIN',
    supportedCurrencies: ['INR', 'USD', 'EUR', 'GBP'],
    invoiceTitle: 'TAX INVOICE',
    appBrandName: 'SelfAccounting.AI',
    complianceBody: 'GST',
    emailBrandName: 'SelfAccounting.AI',
  },
};
